- name: add overlay
  modprobe:
    name: overlay
    state: present

- name: add br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: copy 99-kubernetes-cri.conf
  copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

- name: apply kernel params
  shell: sysctl --system

- name: add crio repos
  yum_repository:
    name: crio
    description: "crio repo"
    baseurl: https://cbs.centos.org/repos/paas7-crio-115-release/x86_64/os/

- name: install crio
  yum:
    name: cri-o
    disable_gpg_check: yes

- name: start crio
  systemd:
    name: crio
    state: restarted
    enabled: yes

