- name: copy 99-kubernetes-cri.conf
  copy:
    src: containerd.conf
    dest: /etc/modules-load.d/containerd.conf

- name: add overlay
  modprobe:
    name: overlay
    state: present

- name: add br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: copy 99-kubernetes-cri.conf
  copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

- name: apply kernel params
  shell: sysctl --system

