---

- name: install packages
  yum:
    name: "{ item }"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: add docker repository
  yum_repository:
    name: docker
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker ce.
  yum:
    name: docker-ce-18.06.2.ce
    state: latest

- name: create /etc/docker
  file:
    path: /etc/docker
    state: directory

